apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-pvrd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-clpx-tenant/rhtap-demo-app/hacbs-test-project-pvrd@sha256:841895aeabaf3727788951ed70a4ee5b23d3b22409048082daeaef0411d13836
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
